### ISSUE TITLE
GraphQL introspection failure on Optional[Record] field

### ISSUE THREAD

**Issue by anxolerd** [vmagamedov/hiku#29]
# Short description

When Field of type `Optional[Record[...]]` is present in graph, introspection query performed by [graphiql](https://github.com/graphql/graphiql) fails with error.

# Reproducing

## Environment
```Python 3.6.4```

## Dependencies
(obtained by `pip install hiku graphql-core`)
```
graphql-core==2.0
Hiku==0.4.1
promise==2.1
Rx==1.6.0
six==1.11.0
typing==3.6.2
```
## Code

```python
import random

from hiku.graph import Graph, Root, Field
from hiku.types import Optional, Record, String

from hiku.engine import Engine
from hiku.result import denormalize
from hiku.executors.sync import SyncExecutor
from hiku.readers.graphql import read

from hiku.graph import apply
from hiku.introspection.graphql import GraphQLIntrospection


def config_resolver(fields):
    if random.uniform(0, 1) < 0.5:  # Some actual condition
        return [None]
    return [{'foo': 'bar'}]


Config = Record[{'foo': String}]


graph = Graph([
    Root([
        Field('config', Optional[Config], config_resolver),
    ])
])
graph = apply(graph, [GraphQLIntrospection()])


hiku_engine = Engine(SyncExecutor())

# The following is simplified version of query performed by GraphiQL
query = '''
  query IntrospectionQuery {
    __schema {
      types {
        name
        fields(includeDeprecated: true) {
          name
          type {
            name
          }
        }
      }
    }
  }
'''
query = read(query)
result = hiku_engine.execute(graph, query)
simple_result = denormalize(graph, result, query)
print(simple_result)
```

## Actual result

Execution fails with the following traceback:

```
Traceback (most recent call last):
  File "graph.py", line 50, in <module>
    result = hiku_engine.execute(graph, query)
  File "/home/oleksandr/.pyenv/versions/hikubug/lib/python3.6/site-packages/hiku/engine.py", line 360, in execute
    return self.executor.process(queue, q)
  File "/home/oleksandr/.pyenv/versions/hikubug/lib/python3.6/site-packages/hiku/executors/sync.py", line 17, in process
    queue.progress(queue.__futures__)
  File "/home/oleksandr/.pyenv/versions/hikubug/lib/python3.6/site-packages/hiku/executors/queue.py", line 38, in progress
    callback()
  File "/home/oleksandr/.pyenv/versions/hikubug/lib/python3.6/site-packages/hiku/engine.py", line 314, in <lambda>
    fut.result())
  File "/home/oleksandr/.pyenv/versions/hikubug/lib/python3.6/site-packages/hiku/engine.py", line 319, in process_link
    result = list(result)
  File "/home/oleksandr/.pyenv/versions/hikubug/lib/python3.6/site-packages/hiku/introspection/graphql.py", line 184, in field_type_link
    yield type_ident.visit(field.type)
  File "/home/oleksandr/.pyenv/versions/hikubug/lib/python3.6/site-packages/hiku/types.py", line 242, in visit
    return obj.accept(self)
  File "/home/oleksandr/.pyenv/versions/hikubug/lib/python3.6/site-packages/hiku/types.py", line 99, in accept
    return visitor.visit_optional(cls)
  File "/home/oleksandr/.pyenv/versions/hikubug/lib/python3.6/site-packages/hiku/introspection/graphql.py", line 34, in visit_optional
    return self.visit(obj.__type__).of_type
AttributeError: 'NoneType' object has no attribute 'of_type'
```

## Expected result

Introspection query succeeded without errors.

# Investigation

After some minor investigations, it was determined that error is hidden in [`TypeIdent` class ](https://github.com/vmagamedov/hiku/blob/6108554/hiku/introspection/graphql.py#L28-L49), which does not provide overloaded `visit_record` method, which should return type of record. Moreover this means, that for any graph with a field of type `Record` introspection query provided would return incorrect results.

**Comment by vmagamedov** [comment]
@anxolerd can you confirm that introspection doesn't fails after it was fixed in 22298a0?

**Comment by anxolerd** [comment]
@vmagamedov, I confirm, that error does not happen as long as `Root` node contains at least one field of GraphQL-supported types (like `String` or `Integer`) or has a `Link` to other node. Still, `Record` field cannot be introspected, which is not critical for now.

At the same time, code provided to reproduce the issue still fails but with other kind of error:
```
Traceback (most recent call last):
  File "graph.py", line 51, in <module>
    result = hiku_engine.execute(graph, query)
  File "/home/oleksandr/.pyenv/versions/hikubug/lib/python3.6/site-packages/hiku/engine.py", line 360, in execute
    return self.executor.process(queue, q)
  File "/home/oleksandr/.pyenv/versions/hikubug/lib/python3.6/site-packages/hiku/executors/sync.py", line 17, in process
    queue.progress(queue.__futures__)
  File "/home/oleksandr/.pyenv/versions/hikubug/lib/python3.6/site-packages/hiku/executors/queue.py", line 38, in progress
    callback()
  File "/home/oleksandr/.pyenv/versions/hikubug/lib/python3.6/site-packages/hiku/engine.py", line 314, in <lambda>
    fut.result())
  File "/home/oleksandr/.pyenv/versions/hikubug/lib/python3.6/site-packages/hiku/engine.py", line 319, in process_link
    result = list(result)
  File "/home/oleksandr/.pyenv/versions/hikubug/lib/python3.6/site-packages/hiku/introspection/graphql.py", line 157, in type_fields_link
    'schema type'.format(ident))
TypeError: Node "Root" does not contain any typed field, which is not acceptable for GraphQL in order to define schema type
```
While the error message is quite descriptive and verbose, I believe this kind of limitation (inability to introspect `Record` fields in GraphQL as well as inability to introspect graph, which only has `Record` fields) should be reflected in the [corresponding documentation](https://hiku.readthedocs.io/en/latest/graphql.html#introspection).

**Comment by vmagamedov** [comment]
Added a note to the [documentation](https://hiku.readthedocs.io/en/latest/graphql.html#introspection)

**Comment by anxolerd** [comment]
Amazing, thanks!

Can this issue be closed, or there is some reason you'd like to keep this open for?

**Comment by vmagamedov** [comment]
Assuming into account your last comment I think I can now close this issue.
